### PR TITLE
Dark mode

### LINKED ISSUE #298: Dark theme
Not something that you couldn't live without, but I would really appreciate it! Please add dark theme.

### PR DESCRIPTION
**Pull request by TheLastProject**
Fixes #298. Defaults to whatever the system theme is. When changing the value in settings, instantly swaps theme.

Yes, this is really all that needed to be done. Android did a pretty good job at making dark themes possible easily.

Screenshot_1575300538
Screenshot_1575300550
Screenshot_1575300553
Screenshot_1575300557
Screenshot_1575300567
Screenshot_1575300569
Screenshot_1575300574
Screenshot_1575303009

---
This change is [Reviewable](https://reviewable.io/reviews/brarcher/loyalty-card-locker/322)

### CODE REVIEW

**Comment by brarcher** [comment]
Experimenting with this on an emulator, I find that if the dark theme setting is configured, then the app is launched clean, it works as expected. However, if the app was running already when the dark mode setting is changed, the app may not take the theme or may do so improperly. Here is an example.

1. System in light mode, app in light mode
2. Launch app, enter app settings
3. Configure app to use dark mode
4. Click back to go to main app activity

image

Note that the title text is really dark. A similar situation happens when switching from dark to light.

image

I'm not sure yet what is causing this behavior on only what appears to be the card title text. (The note text is correct). Are you able to duplicate this on your test device or emulator?

**Comment by TheLastProject** [comment]
I did run into this issue earlier but I thought I fixed it. Seems I did miss a case. I'll take another look at it, thank you

**Comment by TheLastProject** [comment]
I'll deal with the code comments soon, thanks for reviewing.

>I've only a few comments on the code. Let me know if you track down the theme change issue I mentioned, and I'll take a look again.

The issue became less prevalent with recent commits, but it still does occur on some elements (like the border around the about webview). I'm not sure why that happens so it may take some time until I can figure that out, if ever. I will notify you if I believe I found it though.

**Comment by TheLastProject** [comment]
Because a picture is worth more than a thousand words, this is the issue I mean: the dialog uses a dark theme after switching to light theme. I am still going to try to fix this but it... feels like a pretty weird issue.

photo_2019-12-05_20-23-23

**Comment by TheLastProject** [comment]
I've only ever seen it go wrong for the very specific scenario you mentioned, and I managed to fix that so it only bugs out the about dialog now:

1. System in light mode, app in light mode
2. Launch app, enter app settings
3. Configure app to use dark mode
4. Click back to go to main app activity

**Comment by TheLastProject** [comment]
Reviewable keeps crashing whenever I try to log in on it now, so I can't leave my reply there...

Anyway, it seems you're completely right.

While I don't believe all the padding is intended because some of it is kinda absurd:
photo_2019-12-08_18-07-09

I tried changing the code to ensure that 20 pixels of padding remains, so it only removes the absurd padding:
photo_2019-12-08_18-07-11

But the 1D code there still didn't scan (but the QR code did)!

So it indeed seems some of the codes really need all the padding they are given and because doing this only for some codes and not others will very likely lead us to some edge cases with certain scanners, I've reverted the code to clean up the rectangles.

**Comment by TheLastProject** [comment]
Yeah, I indeed reverted it.

**Comment by brarcher** [comment]
> Yeah, I indeed reverted it.

Sorry, did not see your reply initially. Sounds good!

**Comment by brarcher** [comment]
Thanks for adding this feature!

**Comment by TheLastProject** [comment]
And thank you for reviewing, testing and accepting it :)

**Pull request merged**
