### PR TITLE
Icon V2

### PR DESCRIPTION
**Pull request by betsythefc**
Let me know if this one is better :)

### CODE REVIEW

**Comment by brarcher** [comment]
Is the image a card from a keyring?

image

If so, I like the concept. Is the grey circle around the card part of the icon?

**Comment by betsythefc** [comment]
Thats was the idea yeah!
And the circle is part of the icon.

**Comment by brarcher** [comment]
Do you think putting a 'hole' on the side so it looks more like a keyring card would be too much, or that it is fine as is?

**Comment by betsythefc** [comment]
Sure, I'll resize the barcode and put a hole, I'll have it done tomorrow :)

By the way, is there an easy way to amend my pull request or should I close it and make a new one?

**Comment by brarcher** [comment]
I'm not sure how you are creating the commits themselves. If one were using git on the command line one could simply push to the same branch again, and I think that will update the pull request.

**Comment by betsythefc** [comment]
Before I do another pull request, how is this icon:
ic_launcher

**Comment by betsythefc** [comment]
@brarcher, You were right, I pushed to my repo/branch and it updated here as well.

**Comment by brarcher** [comment]
I like it!

On December 5, 2016 11:43:38 PM EST, Bryce McNab <notifications@github.com> wrote:
>Before I do another pull request, how is this icon:
>ic_launcher
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/brarcher/loyalty-card-locker/pull/75#issuecomment-265059417

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by betsythefc** [comment]
@brarcher Awesome! Let's merge the branch

**Pull request merged**
