### PR TITLE
Fix dark mode scanning issues

### LINKED ISSUE #328: Couldn't scan at store with dark theme
Just so I don't forget to test this again. Local grocery store, barcode type EAN_13. Code scans fine on light theme.

### PR DESCRIPTION
**Pull request by TheLastProject**
Fixes #328, hopefully. Will leave this pull request in WIP until I have confirmed it does work in the store.

### CODE REVIEW

**Comment by TheLastProject** [comment]
No longer WIP, just scanned it at the store and it worked great on the dark theme too :)

**Comment by TheLastProject** [comment]
So I found out today (by running a version of the app without this patch) that the code does scan eventually if you fiddle around enough. But this patch makes it scan instantly like on the light theme

**Comment by TheLastProject** [comment]
I actually managed to successfully scan with dark mode without this patch several times now. I guess I just had bad luck that one time. Closing this pull request.

**Comment by TheLastProject** [comment]
I really think this January 16th review relates to this issue: https://play.google.com/store/apps/details?id=protect.card_locker&reviewId=gp%3AAOqpTOHzh05DfQXkszJjd44vsd_rQTPDkPntBJLhyHOWa3OfTSlVdi0yOEZCsuUcHUzPbCfRMLJ-pCPW_eGSx8Q

I still constantly need to switch to light mode at my local supermarket too to have the code scanned.

Seeing this example, CVS has the exact same barcode format as my grocery store too: 
image

Note the extra white spacing around the barcode that this pull requests will add.

**Comment by brarcher** [comment]
Sounds good. I'll merge this change in and cut a release.

**Review by pejfat08-rgb — APPROVED** [review]

**Review by pejfat08-rgb — APPROVED** [review]

**Pull request merged**
