### PR TITLE
Add a note field

### PR DESCRIPTION
**Pull request by brarcher**

### CODE REVIEW

**Comment by brarcher** [comment]
This merge request adds a Note field for loyalty cards. It adds two new strings. One needs to be translated, which is the title to the note field:
```
<string name="note">Note</string>
```
And a second, which represents how the store name and note will be displayed together, can be kept as is if it makes sense:
```
<string name="storeNameAndNoteFormat">%1$s - %2$s</string>
```

@Airon90 Would you be so kind as to provide an Italian translation for the Note field, and confirm that the storeNameAndNoteFormat string is OK as it (or provide an alternative)?

@PanderMusubi Would you be so kind as to provide a Dutch translation for the Note field, and confirm that the storeNameAndNoteFormat string is OK as it (or provide an alternative)?

Thanks!

**Comment by PanderMusubi** [comment]
"Note" in Dutch is "Notitie"

**Comment by brarcher** [comment]
Using Google to translate "Note" to Italian results in "Nota". If this is incorrect, please let me know, @Airon90.

**Comment by Airon90** [comment]
Excuse me but I don't have spare time right now to change the file! I'm sorry! "Note" in Italian is "Nota" but it is to use better the plural, "Note"

**Comment by brarcher** [comment]
No problem. I'll update the translation to "Note". Thanks!

**Pull request merged**
