### PR TITLE
Delete confirmation

### PR DESCRIPTION
**Pull request by brarcher**
Add a confirmation before deleting card
    
https://github.com/brarcher/loyalty-card-locker/issues/53

### CODE REVIEW

**Comment by brarcher** [comment]
Hello @Airon90 and @PanderMusubi!

The following pull request adds a confirmation dialog before deleting a loyalty card. This results in adding the following strings:
```
<string name="confirm">Confirm</string>
<string name="deleteTitle">Remove Loyalty Card</string>
<string name="deleteConfirmation">Please confirm that you want to delete this card.</string>
```
Could you please provide translations for these two strings?

Thanks!

**Comment by PanderMusubi** [comment]
Dutch:

    <string name="confirm">Bevestig</string>
    <string name="deleteTitle">Verwijder kaart</string>
    <string name="deleteConfirmation">Bevestig deze kaart te verwijderen.</string>

**Comment by Airon90** [comment]
Here my transations:

```
<string name="confirm">Conferma</string>
<string name="deleteTitle">Rimuovi carta fedeltà</string>
<string name="deleteConfirmation">Conferma che vuoi eliminare questa carta.</string>
```

**Comment by brarcher** [comment]
Thanks, @PanderMusubi and @Airon90!

**Comment by Airon90** [comment]
You're welcome! :)

**Pull request merged**
