### PR TITLE
First run intro wizard

### PR DESCRIPTION
**Pull request by brarcher**
screenshot_20170618-230717
screenshot_20170618-230726
screenshot_20170618-230729
screenshot_20170618-230732
screenshot_20170618-230736
screenshot_20170618-230739

### CODE REVIEW

**Comment by brarcher** [comment]
Hi @arno-github, @lgasp, @techwebpd, @Clonewayx, @pbeckmann, @Airon90 and @PanderMusubi:

This request added some strings which are used in a wizard which is shown the first time the app is launched. This will give an explanation to users about how to use the application. Images of the wizard are above.

Currently the string is in English in the different strings.xml files with the line . If any are interested in updating translations, please create a merge request with the changes, or attach an updated file and I'll add it.

Thanks!

**Comment by arno-github** [comment]
I'm not totally satisfied with the translated strings, but it's better than nothing ;-)
If I find better strings I'll update!
This is the french translation:
[strings.txt](https://github.com/brarcher/loyalty-card-locker/files/1089417/strings.txt)

**Comment by pbeckmann** [comment]
I'm currently low on time. I hope that I can provide you the German translation on Saturday or Sunday.

**Comment by brarcher** [comment]
No problem, @pbeckmann. I'll hold off on cutting a release until Sunday. (:

**Comment by brarcher** [comment]
Thanks, @arno-github!

**Pull request merged**
