### PR TITLE
Move barcode to top on tap

### LINKED ISSUE #143: Move barcode closer to top/bottom of screen
I would like to scan my library card at a self-checkout station. The laser is within an indentation in the side of the checkout station. 

With the current layout the 1D barcode is quite far from both top and bottom of the screen so the laser doesn't reach the barcode. 

I read a discussion in another issue about making the barcode full screen when you tap on it. That would be helpful for my use case. 

I realise my use case is unusual and understand if it is not something you want to support.

### PR DESCRIPTION
**Pull request by TheLastProject**
On a tap of the barcode, moves the barcode to the top of the screen. On another tap, move things back to normal. On the second screenshot, the top bar is normally hidden, it is only visible because creating a screenshot makes it reappear. Fixes #143.

photo_2020-01-19_19-09-08
photo_2020-01-19_19-09-10

---
This change is [Reviewable](https://reviewable.io/reviews/brarcher/loyalty-card-locker/348)

### CODE REVIEW

**Comment by devurandom** [comment]
This also works when rotating screens? Is there a setting to always have it at the edge of the screen?

**Comment by TheLastProject** [comment]
>This also works when rotating screens?

Yeah, but it doesn't fix the barcode sizing issues that sometimes happen in landscape view.

>Is there a setting to always have it at the edge of the screen?

No, because it really hides everything, also the edit button. So letting this be a default would make a lot of features unreachable. It's just a single tap away, though.

**Comment by clach04** [comment]
From quick scan of code (I'm not familiar with the code base) and testing debug build provided for #143 this looks good to me 👍 

For the other questions about about additional features - those would be nice to have but I see those as new enhancements (there are issues open for some of those) that could be done in a different PR.

**Comment by brarcher** [comment]
@TheLastProject, I'm wondering about the barcode entering the status bar. For the 2D barcodes could the app icons interfere with the barcode squares and prevent proper scanning? Should the barcode be below the status bar to prevent scanning issues?

**Comment by TheLastProject** [comment]
The status bar is actually hidden, but Android force-shows it whenever I try to take a screenshot, so I couldn't show it is hidden normally.

**Comment by brarcher** [comment]
> The status bar is actually hidden, but Android force-shows it whenever I try to take a screenshot, so I couldn't show it is hidden normally.

Oh, I see. You are right. Trying that out on an emulator it is working just fine. Neat. (:  

I wonder how a user will discover this feature. (Or almost any feature in the all, really...). Do you think (in a separate PR) adding a new entry to the first start wizard would help? I'm not that familiar with how to help users discover features in apps. Nothing that needs to be solved now, just a thought.

**Comment by TheLastProject** [comment]
The issue with the first start wizard is that existing users probably won't see it and thus still not know about the new features.

Maybe it'll be interesting to add something like https://steemit.com/utopian-io/@andrixyz/using-material-showcase-view-to-tutor-users-in-android-app-development, so we can highlight interesting new features on new releases and guide new users through how to use the app, replacing the first start wizard entirely with such hints?

**Comment by clach04** [comment]
> The status bar is actually hidden, but Android force-shows it whenever I try to take a screenshot, so I couldn't show it is hidden normally.

I can confirm this based on testing my device.

**Pull request merged**
