### PR TITLE
Select import file, allow exported file to be sent

### PR DESCRIPTION
**Pull request by brarcher**
This provides the first half of the request https://github.com/brarcher/loyalty-card-locker/issues/61 by allowing the user to select which file to import.

### CODE REVIEW

**Comment by brarcher** [comment]
@pbeckmann @techwebpd @Clonewayx @PanderMusubi @Airon90 

This pull request adds the ability to pick from the file system which backup file will be imported:

screenshot_2016-12-05-22-48-50
screenshot_2016-12-05-22-49-10
screenshot_2016-12-05-22-49-04

Could translations for the following strings be provided, so that the application may be kept up-to-date?

```
<string name="importExportHelp">Backed up data can allow you to move your cards to another device.</string>
<string name="importSuccessfulTitle">Import successful</string>
<string name="importFailedTitle">Import failed</string>
<string name="exportSuccessfulTitle">Export successful</string>
<string name="exportFailedTitle">Export failed</string>
<string name="exportOptionExplanation">Data is written to the top directory in external storage.</string>
<string name="importOptionFilesystemTitle">Import from filesystem</string>
<string name="importOptionFilesystemExplanation">Choose a specific file from the filesystem.</string>
<string name="importOptionFilesystemButton">From filesystem</string>
<string name="importOptionApplicationTitle">Import from filesystem</string>
<string name="importOptionApplicationExplanation">Use an external application like Dropbox, Google Drive, or your favorite file manager to open a file.</string>
<string name="importOptionApplicationButton">Use external application</string>
<string name="importOptionFixedTitle">Import from export location</string>
<string name="importOptionFixedExplanation">Import from the same location on the filesystem that is written to on export.</string>
<string name="importOptionFixedButton">Use export location</string>
```

You may reply inline, and I'll add the translations to the pull request.

Thanks!

**Comment by Clonewayx** [comment]
<string name="importExportHelp">Zálohování dat vám umožní přesunout vaše uložené karty na jiné zařízení.</string>
    <string name="importSuccessfulTitle">Import proběhl úspěšně</string>
    <string name="importFailedTitle">Import selhal</string>
    <string name="exportSuccessfulTitle">Export proběhl úspěšně</string>
    <string name="exportFailedTitle">Export selhal</string>
    <string name="exportOptionExplanation">Data jsou zapsána do kořenové složky externího uložiště.</string>
    <string name="importOptionFilesystemTitle">Import ze souborového systému</string>
    <string name="importOptionFilesystemExplanation">Vyberte konkrétní soubor v uložišti.</string>
    <string name="importOptionFilesystemButton">Ze souborového systému</string>
    <string name="importOptionApplicationTitle">Import ze souborového systému</string>
    <string name="importOptionApplicationExplanation">K otevření souboru použije externí aplikaci jako Dropbox, Google Drive, nebo vámi preferovaný prohlížeč souborů.</string>
    <string name="importOptionApplicationButton">Použít externí aplikaci</string>
    <string name="importOptionFixedTitle">Import z umístění exportu</string>
    <string name="importOptionFixedExplanation">Import ze stejné složky souborového systému do níž se zapisuje při exportu.</string>
    <string name="importOptionFixedButton">Použít složku exportu</string>
    <string name="sendLabel">Odeslat&#8230;</string>

**Comment by PanderMusubi** [comment]
Dutch (NL)

    <string name="importExportHelp">Data die is geback-upt maakt het mogelijk om je klantenkaarten naar een ander apparaat te verplaatsen.</string>
    <string name="importSuccessfulTitle">Importeren succesvol</string>
    <string name="importFailedTitle">Importeren mislukte</string>
    <string name="exportSuccessfulTitle">Exporteren succesvol</string>
    <string name="exportFailedTitle">Exporteren mislukt</string>
    <string name="exportOptionExplanation">Data is weggeschreven naar de hoogste map in externe opslag.</string>
    <string name="importOptionFilesystemTitle">Importeer van filesysteem</string>
    <string name="importOptionFilesystemExplanation">Kies een specifiek bestand van het filesysteem.</string>
    <string name="importOptionFilesystemButton">Van filesysteem</string>
    <string name="importOptionApplicationTitle">Importeer van filesysteem</string>
    <string name="importOptionApplicationExplanation">Gebruik een externe applicatie zoals Dropbox, Google Drive of je favoriete bestandsbeheer om een bestand te openen.</string>
    <string name="importOptionApplicationButton">Gebruik externe applicatie</string>
    <string name="importOptionFixedTitle">Importeer van exporteerlocatie</string>
    <string name="importOptionFixedExplanation">Importeer van zelfde locatie op het filesysteem waar tijdens exporteren naar geschreven is.</string>
    <string name="importOptionFixedButton">gebruik exporteerlocaite</string>
    <string name="sendLabel">Verzend&#8230;</string>

**Comment by pbeckmann** [comment]
Hey,
german strings are attached.

[strings-de.txt](https://github.com/brarcher/loyalty-card-locker/files/634217/strings-de.txt)

**Comment by Airon90** [comment]
«All checks have failed»
Do I wait to translate in Italian or do I translate although the error message?

**Comment by brarcher** [comment]
The checks failed because not all of the language translations are complete. It is ok to translate the strings I mentioned earlier. When all of the languages have their translations the checks should pass. (:

**Comment by Airon90** [comment]
Italian (it). I'm not sure about latest keys.

```
<string name="importExportHelp">Fare il backup dei dati ti permette di spostare le tue tessere da un dispositivo ad un altro.</string>
<string name="importSuccessfulTitle">Importazione avvenuta con successo</string>
<string name="importFailedTitle">Importazione fallita</string>
<string name="exportSuccessfulTitle">Esportazione avvenuta con successo</string>
<string name="exportFailedTitle">Esportazione fallita</string>
<string name="exportOptionExplanation">I dati sono stati scritti nella cartella principale della memoria esterna.</string>
<string name="importOptionFilesystemTitle">Importa dal file system</string>
<string name="importOptionFilesystemExplanation">Scegli un file dal file system.</string>
<string name="importOptionFilesystemButton">Dal file system</string>
<string name="importOptionApplicationTitle">Importa dal file system</string>
<string name="importOptionApplicationExplanation">Usa un'applicazione esterna come Dropbox, Google Drive o il tuo file manager preferito per aprire il file.</string>
<string name="importOptionApplicationButton">Usa un'applicazione esterna</string>
<string name="importOptionFixedTitle">Importa da un altro posto</string>
<string name="importOptionFixedExplanation">Importa dallo stesso posto del file system dove si è esportato.</string>
<string name="importOptionFixedButton">Usa luogo dell'esportazione</string>
<string name="sendLabel">Invia&#8230;</string>
```

**Comment by arno-github** [comment]
French strings

<string name="importExportHelp">Exporter vos données vous permet de récupérer vos cartes sur un autre appareil.</string>
<string name="importSuccessfulTitle">Importé avec succès</string>
<string name="importFailedTitle">Échec de l\'import</string>
<string name="exportSuccessfulTitle">Exporté avec succès</string>
<string name="exportFailedTitle">Échec de l\'export</string>
<string name="exportOptionExplanation">Les données sont sauvegardées à la racine du stockage externe.</string>
<string name="importOptionFilesystemTitle">Importer depuis le système de fichiers.</string>
<string name="importOptionFilesystemExplanation">Choisissez le fichier à importer.</string>
<string name="importOptionFilesystemButton">Système de fichiers</string>
<string name="importOptionApplicationTitle">Importer depuis le système de fichiers</string>
<string name="importOptionApplicationExplanation">Utilisez une application externe comme Dropbox, Google Drive, ou votre gestionnaire de fichiers favori pour ouvrir un fichier.</string>
<string name="importOptionApplicationButton">Application externe</string>
<string name="importOptionFixedTitle">Importer depuis le même emplacement que pour l\'export</string>
<string name="importOptionFixedExplanation">Importe les données depuis le même emplacement que celui défini pour l\'export.</string>
<string name="importOptionFixedButton">Utiliser l\'emplacement de l\'export</string>
<string name="sendLabel">Envoyer&#8230;</string>

**Comment by brarcher** [comment]
The Lithuanian strings are not yet translated. Instead, the English strings are in the strings-lt.xml file with the tag
```
<!-- needs translated -->
``` 
@techwebpd feel free to submit a merge request updating the missing translations.

**Pull request merged**
