### PR TITLE
Add option to lock screen orientation

### PR DESCRIPTION
**Pull request by brarcher**
https://github.com/brarcher/loyalty-card-locker/issues/114

### CODE REVIEW

**Comment by brarcher** [comment]
Hi @arno-github, @lgasp, @techwebpd, @Clonewayx, @pbeckmann, @airon90 and @PanderMusubi:

This request adds some strings which are used in a feature which locks the screen orientation. This is to help prevent the screen from rotating when handing the phone to a clerk to scan a barcode.

The strings are marked with:
```
<!-- NEEDS TRANSLATED -->
```

If any are interested in updating translations, please create a merge request with the changes, or attach an updated file and I'll add it.

Thanks!

**Comment by PanderMusubi** [comment]
Could you please set up a translation project on Transifex or other translation website? In that way, translations will go much quicker and can be made an reviewed in a more efficient way.

**Comment by brarcher** [comment]
I've setup a project here: https://www.transifex.com/na-243/loyalty-card-locker/dashboard/

I'm not sure what needs to be done to add someone who can contribute a translation. Do I need to have your email address to add you?

**Comment by PanderMusubi** [comment]
I just requested to become a translator. Think you just have to approve that. Perhaps it is also possible for you to add translators. Probably best is to notify all translaters to go there and also request access.

**Comment by brarcher** [comment]
I've accepted your request to join. In the future when new strings are added, is all I need to do is update the English strings on the site, and everyone will be notified automatically? Then, before I make a release just take the most recent translations from the site and commit them?

**Comment by PanderMusubi** [comment]
Notification depends on how translaters have configured this in Transifex. However, more people can make translations in this way.

Yes, before each release, simple used the latest version from Transifex.

**Pull request merged**
