### PR TITLE
Display barcode format

### PR DESCRIPTION
**Pull request by sergiowalls**
This PR is made by request of #308 . It will display a text with the barcode format on the loyalty card detail view (only for the loyalty cards with barcode).

Screenshot:
image

No tests were added because I didn't find any specific tests for view checks.

---
This change is [Reviewable](https://reviewable.io/reviews/brarcher/loyalty-card-locker/333)

### CODE REVIEW

**Comment by brarcher** [comment]
Thanks for your interest in improving this app.

I've a few questions about the feature in https://github.com/brarcher/loyalty-card-locker/issues/308. Namely, I think it could be useful to show the barcode type when manually entering a barcode, as well as in the edit screen. I'm asking if there is a good use case for showing the barcode type when viewing a barcode. If you have any ideas or suggestions, let's have the discussion in https://github.com/brarcher/loyalty-card-locker/issues/308.

**Comment by sergiowalls** [comment]
Hey! I did some changes, find below in the attached pictures:

Barcode format is displayed on the select barcode view.
Screenshot_20200106-214905_Loyalty Card Keychain

It is shown in the edit loyalty card view
Screenshot_20200106-215409_Loyalty Card Keychain

The text field is hidden if none selected
Screenshot_20200106-214849_Loyalty Card Keychain

And in the add view is hidden until user picks one
Screenshot_20200106-214928_Loyalty Card Keychain

Sorry for the pictures in spanish.

**Comment by sergiowalls** [comment]
Thanks for the feedback. I made the requested changes. However now there are two tests failing but I don't get why. Can you take a look on it? The details in the TravisCI job are not very helpful.

As I don't have an account on _reviewable.io_ I will answer here why I removed the check of the type of the barcode:

In the XML for the edit activity, the barcode field is wrapped into a table row, that element is the one which is displayed or hidden depending on the specific loyalty card. That caused me some problems while testing and I just decided to remove that check. Of course if you see a better approach feel free to change it!

**Comment by brarcher** [comment]
> The details in the TravisCI job are not very helpful.

The TravisCI job runs basically runs the following command and reports the result:
```
./gradlew assembleRelease testReleaseUnitTest lintRelease findbug
```

Are you able to execute the unit tests locally and reproduce the failures? It will probably be easier to track down running them in Android Studio, if that is an option. 

Running it in Android Studio there is a more complete stack trace which is useful:
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

	at org.robolectric.shadows.ShadowActivity$ActivityInvoker.with(ShadowActivity.java:717)
	at org.robolectric.shadows.ShadowActivity.receiveResult(ShadowActivity.java:534)
	at protect.card_locker.LoyaltyCardViewActivityTest.selectBarcodeWithResult(LoyaltyCardViewActivityTest.java:207)
	at protect.card_locker.LoyaltyCardViewActivityTest.removeBarcodeFromLoyaltyCard(LoyaltyCardViewActivityTest.java:606)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:600)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:260)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.robolectric.shadows.ShadowActivity$ActivityInvoker.with(ShadowActivity.java:715)
	... 28 more
Caused by: java.lang.IllegalArgumentException: No enum constant com.google.zxing.BarcodeFormat._NO_BARCODE_
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.google.zxing.BarcodeFormat.valueOf(BarcodeFormat.java:24)
	at protect.card_locker.LoyaltyCardEditActivity.onResume(LoyaltyCardEditActivity.java:241)
	at protect.card_locker.LoyaltyCardEditActivity.onActivityResult(LoyaltyCardEditActivity.java:513)
	... 33 more
```

>As I don't have an account on reviewable.io I will answer here why I removed the check of the type of the barcode:

Thats fine. I use reviewable.io because it helps my looking at diffs. You do not need to use it if you do not want to. (:


> In the XML for the edit activity, the barcode field is wrapped into a table row, that element is the one which is displayed or hidden depending on the specific loyalty card. That caused me some problems while testing and I just decided to remove that check. Of course if you see a better approach feel free to change it!

The check which was removed, namely
```
checkFieldProperties(activity, R.id.barcodeType, View.GONE, barcodeType);
```
asserted two important things in this context: (1) the view's visibility and (2) its contents. Could not the assertion be split into two so that the nature of the assertion is still present? Namely, have a check for the visibility of R.id.barcodeTypeTableRow (and the other status changes in showBarcode()/hideBarcode()) and have a check for the contents of R.id.barcodeTypeView. Would that do?

**Comment by sergiowalls** [comment]
Thanks for the execution details, it has been impossible for me to run the tests on Windows environment. I think the error is related to the path separator, the output is:

`Illegal character in opaque part at index 11: jar:file:C:\Users\Sergio\Development\loyalty-card-locker\app\build\intermediates\apk_for_local_test\debugUnitTest\packageDebugUnitTestForUnitTest\apk-for-local-test.ap_`

Anyway, I found the issue and it's solved on e1f4ed65bb0c53d1a6c17de36daf67e870cc7245

I also restored the check for the barcode data on aa2ccac22bac6c3c5a1fd11ed0c951a124d1ea62 but I didn't add the check for the visibility of the table row due to lack of time and the inconveniences of running the tests locally. 

Can we merge this PR? It's a bit annoying to keep merging the branch with the changes from master because of the problem with the test execution.

**Comment by brarcher** [comment]
> Can we merge this PR? It's a bit annoying to keep merging the branch with the changes from master because of the problem with the test execution.

I'll try to do it this week. Thanks for your patience.

**Comment by brarcher** [comment]
Thanks for adding this feature!

**Pull request merged**
