### PR TITLE
Copy card id to clipboard

### PR DESCRIPTION
**Pull request by brarcher**
Allow long-click of card to copy id to clipboard
    
https://github.com/brarcher/loyalty-card-locker/issues/49

### CODE REVIEW

**Comment by brarcher** [comment]
Hello @Airon90 and @PanderMusubi!

The following pull request adds support for copying a card ID to the clipboard if one long-clicks the card item from the main view. This results in adding the following two strings:
```
<string name="copy_to_clipboard">Copy ID to clipboard</string>
<string name="copy_to_clipboard_toast">Card ID copied to clipboard</string>
```
Could you please provide translations for these two strings?

Thanks!

**Comment by Airon90** [comment]
Sorry, I don't have time to do the correct edit:
<string name="copy_to_clipboard">Copia ID negli appunti</string>
<string name="copy_to_clipboard_toast">ID della carta copiato negli appunti</string>

**Comment by brarcher** [comment]
> Sorry, I don't have time to do the correct edit

Comments are just fine. Thanks!

**Comment by brarcher** [comment]
@PanderMusubi, I've attempted to translate the strings to Dutch. If any of these are inaccurate, please let me know.
```
<string name="copy_to_clipboard">Kopieer ID naar het klembord</string>
<string name="copy_to_clipboard_toast">Card ID gekopieerd naar het klembord</string>
```

**Comment by PanderMusubi** [comment]
<string name="copy_to_clipboard">Kopieer het ID naar het klembord</string>
    <string name="copy_to_clipboard_toast">Het ID is naar het klembord gekopieerd</string>

**Comment by brarcher** [comment]
Thanks @PanderMusubi!

**Pull request merged**
