### PR TITLE
Add german translation.

### PR DESCRIPTION
**Pull request by pbeckmann**
yahh, i added the german translation as good as i can.

### CODE REVIEW

**Comment by Entze** [comment]
Are you a native speaker?

**Comment by pbeckmann** [comment]
Yes i am a native german speaker. And i would prefer staying with the informal variant as I think it is a better experience for the user.

**Comment by Entze** [comment]
That would be different for every app then but okay. I would also point out that there are some strings untranslated.

**Comment by pbeckmann** [comment]
You are welcome to open another pull request, then I'll close mine. I'm currently too stressed, and just had the five nminutes to do it.

**Pull request closed without merging**
