### PR TITLE
Allow manual barcode entry

### PR DESCRIPTION
**Pull request by brarcher**

### CODE REVIEW

**Comment by brarcher** [comment]
@Airon90 and @PanderMusubi, this pull request adds the ability to add a barcode manually. There are several more strings which need to be translated. Would you mind providing the appropriate translations for Italian and Dutch when there is time? The strings are as follows:

```
<string name="enterCard">Enter Card</string>
<string name="selectBarcodeTitle">Select Barcode</string>
<string name="enterBarcodeInstructions">Enter the barcode value then select the image which represents the barcode you want to use</string>
```

Thanks!

**Comment by brarcher** [comment]
Italian translations pulled in from https://github.com/brarcher/loyalty-card-locker/pull/45/commits/54ac3b0211b6198a5f87d111f96fc16af54298e5. Thanks!

**Comment by PanderMusubi** [comment]
Dutch:

    <string name="enterCard">Voer kaart in</string>
    <string name="selectBarcodeTitle">Selecteer barcode</string>
    <string name="enterBarcodeInstructions">Voer de waarde van de barcode in en kies daarna de afbeelding die de barcode die je wil gebruiken representeert</string>

**Comment by brarcher** [comment]
Thanks for the translations!

**Pull request merged**
